GOATS-684: Skip building docs if no changes.

diff --git a/.readthedocs.yaml b/.readthedocs.yaml
--- a/.readthedocs.yaml
+++ b/.readthedocs.yaml
@@ -18,6 +18,18 @@ build:
       - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --only-group docs
     install:
       - "true"
+    post_checkout:
+      # Cancel building pull requests when there aren't changed in the docs directory or YAML file.
+      # You can add any other files or directories that you'd like here as well,
+      # like your docs requirements file, or other files that will change your docs build.
+      #
+      # If there are no changes (git diff exits with 0) we force the command to return with 183.
+      # This is a special exit code on Read the Docs that will cancel the build immediately.
+      - |
+        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- docs/readthedocs/ .readthedocs.yaml;
+        then
+          exit 183;
+        fi
 
 sphinx:
   configuration: docs/readthedocs/source/conf.py
